### ISSUE TITLE
Multiple ControlCenter instances?

### ISSUE THREAD

**Issue by ebekker** [davidfowl/CommandAndControl#3]
So how would you scale this sample to support multiple CC instances?

Presumably, you could put multiple instances behind a single WebSocket-aware load balancer, so each agent can maintain a connection to any one instance at a time.

But you also need to maintain a collective state of all the agents across the servers that any CC instance can inspect.  Is this just using some shared messaging back plain like Azure Service Bus so all instances are aware of any state changes?  Or perhaps a better approach is a shared state store like a simple SQL DB or Redis?

Or is there something more inherently native to ASP.NET Core to help with this?

**Comment by ebekker** [comment]
Oh, and I'm not counting the Azure SignalR Service, that's cheating :-)  Also not viable in other clouds.

**Comment by davidfowl** [comment]
https://docs.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?view=aspnetcore-6.0
